/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_targetv_ott_FileBrowserService */

#ifndef _Included_com_targetv_ott_FileBrowserService
#define _Included_com_targetv_ott_FileBrowserService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_targetv_ott_FileBrowserService
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_targetv_ott_FileBrowserService__1init
  (JNIEnv *, jobject);

/*
 * Class:     com_targetv_ott_FileBrowserService
 * Method:    _uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_targetv_ott_FileBrowserService__1uninit
  (JNIEnv *, jobject);

/*
 * Class:     com_targetv_ott_FileBrowserService
 * Method:    _readdir
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_targetv_ott_FileBrowserService__1readdir
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     com_targetv_ott_FileBrowserService
 * Method:    _findService
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_targetv_ott_FileBrowserService__1findService
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
